# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

variables:
- name: resourcegroupName
  value: DeployRG-1

stages:
  - stage: Build
    jobs:
      - job: Build

        pool:
          vmImage: ubuntu-latest
  
        steps:
          - task: AzureCLI@2
            name: 'buildBicepfile'
            inputs:
              azureSubscription: 'AzureConnection'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az bicep build --file ''03Improved_pipeline/StorageAccount.bicep'''

  - stage: DeploytoTest
    jobs:
      - job: DeploytoTest

        pool:
          vmImage: ubuntu-latest
  
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          name: deploy
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureConnection'
            subscriptionId: '71818d77-4e18-47c8-8c36-b7af11e60bde'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resourcegroupName)'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '03Improved_pipeline/StorageAccount.bicep'
            overrideParameters: '-storageAccountPrefix "csTest"'
            deploymentMode: 'Incremental'

  - stage: DeploytoProd
    jobs:
      - job: DeploytoProd

        pool:
          vmImage: ubuntu-latest
  
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          name: deploy
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureConnection'
            subscriptionId: '71818d77-4e18-47c8-8c36-b7af11e60bde'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resourcegroupName)'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '03Improved_pipeline/StorageAccount.bicep'
            overrideParameters: '-storageAccountPrefix "csprod"'
            deploymentMode: 'Incremental'
